AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nodejs-layer-config-testing

  Sample SAM Template for nodejs-layer-config-testing
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: newrelic-lambda-wrapper.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          NEW_RELIC_ACCOUNT_ID: "your-account-id"
          NEW_RELIC_LAMBDA_HANDLER: "app.handler"
          NEW_RELIC_LICENSE_KEY: "your-license-key"
          NEW_RELIC_LOG_ENDPOINT: "your-log-endpoint"
          NEW_RELIC_TELEMETRY_ENDPOINT: "your-telemetry-endpoint"
          NEW_RELIC_USE_ESM: "true"
          NEW_RELIC_EXTENSION_LOG_LEVEL: "DEBUG"
          NEW_RELIC_EXTENSION_SEND_EXTENSION_LOGS: "false"
          NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: "false"
          NEW_RELIC_LAMBDA_EXTENSION_ENABLED: "true"
      
      Layers:
        # This layer includes the New Relic Lambda Extension, a sidecar process that sends telemetry
        - !Sub arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS22X:8
      Policies:
        # This policy allows the lambda to know the value of the New Relic licence key. We need this so
        # that we can send telemetry back to New Relic
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !ImportValue NewRelicLicenseKeySecret-NewRelic-LicenseKeySecretARN
    

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
